# Generated by Django 4.1.1 on 2022-09-12 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desciption', models.TextField()),
                ('price', models.BigIntegerField()),
                ('cover', models.ImageField(upload_to='cover')),
                ('exist', models.CharField(choices=[('have', 'have'), ('in_order', 'in_order'), ('finish', 'finish')], default='have', max_length=8)),
                ('material', models.CharField(max_length=50)),
                ('place_to_use', models.CharField(max_length=300)),
                ('weight', models.CharField(max_length=200)),
                ('date_time_create', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 6, 53, 25, 960277, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
