# Generated by Django 4.1.1 on 2022-09-13 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 6, 54, 17, 528977, tzinfo=datetime.timezone.utc)),
        ),
    ]
