# Generated by Django 4.1.1 on 2022-09-13 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_product_date_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 6, 58, 55, 924350, tzinfo=datetime.timezone.utc)),
        ),
    ]
