# Generated by Django 4.1.1 on 2022-09-13 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_date_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 7, 2, 0, 653707, tzinfo=datetime.timezone.utc)),
        ),
    ]
