# Generated by Django 4.1.1 on 2022-09-13 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('work_description', models.TextField(verbose_name='work_description')),
                ('work_image', models.ImageField(upload_to='work_image', verbose_name='work_image')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='team_member')),
            ],
            options={
                'verbose_name': 'Aboutus',
            },
        ),
    ]
