# Generated by Django 4.1.1 on 2022-09-13 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='team_member',
        ),
        migrations.AddField(
            model_name='about_us',
            name='team_member',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='team_member'),
        ),
    ]
