# Generated by Django 4.1.1 on 2022-09-13 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0002_remove_about_us_team_member_about_us_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('text', models.TextField(verbose_name='your text')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date_time_create')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'contactmessage',
            },
        ),
    ]
